version: 2.2

jobs:
  build:
    docker:
      - image: cimg/node:16.20.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-

      - run:
          name: Clean project
          command: rm -rf node_modules platforms plugins

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run:
          name: Prepare environment files
          command: |
            cp ./src/environments/environment.ts.example ./src/environments/environment.ts

      - run:
          name: Google services
          command: echo "$GOOGLE_SERVICES" | base64 --decode > google-services.json

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Debug Cordova resolution
          command: |
            which cordova || true
            npx cordova --version
            npm ls cordova || true

      - run:
          name: Add browser platform
          command: npx ionic cordova platform add browser --no-save

      - run:
          name: Build browser
          command: npx ionic cordova build browser --no-interactive --confirm

      - save_cache:
          key: browser-build-cache-{{ checksum "config.xml" }}
          paths:
            - ./www